version: "3.9"
services:
  
  web:
    build: .
    ports:
      - "1323:1323"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - CATSDBTYPE=postgres # postgres or mongo
      - WAIT_HOSTS=postgres:5432,mongo:27017
    #command: sh -c "/wait && /cats"
    depends_on:
      - "postgres"
      - "mongo"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgpass

  mongo:
    image: mongo