version: "3.9"
services:
  
  web:
    build: .
    ports:
      - "1323:1323"
    environment:
      - PG_HOST=postgres
      - MONGO_HOST=mongo
      - CATSDBTYPE=postgres # postgres or mongo
    depends_on:
      - "postgres"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgpass

  mongo:
    image: mongo