apiVersion : apps/v1
kind: Deployment
metadata:
  name: cats-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-app
  template:
    metadata:
      labels:
        app: cats-app
    spec:
      containers:
        - name: cats-app
          image: azurecatsacr3.azurecr.io/cats
          ports:
          - containerPort: 80